# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cookWindow(object):
    def setupUi(self, cookWindow):
        cookWindow.setObjectName("cookWindow")
        cookWindow.resize(1285, 600)
        self.centralwidget = QtWidgets.QWidget(cookWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitleWindow = QtWidgets.QLabel(self.centralwidget)
        self.labelTitleWindow.setGeometry(QtCore.QRect(410, 20, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTitleWindow.setFont(font)
        self.labelTitleWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTitleWindow.setObjectName("labelTitleWindow")
        self.pushButtonCooking = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCooking.setGeometry(QtCore.QRect(520, 130, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonCooking.setFont(font)
        self.pushButtonCooking.setStyleSheet("background-color: rgb(150, 246, 84);\n"
"color: rgb(3, 0, 0);")
        self.pushButtonCooking.setObjectName("pushButtonCooking")
        self.listOrders = QtWidgets.QTextBrowser(self.centralwidget)
        self.listOrders.setGeometry(QtCore.QRect(50, 130, 391, 71))
        self.listOrders.setObjectName("listOrders")
        self.lablOredrs = QtWidgets.QLabel(self.centralwidget)
        self.lablOredrs.setGeometry(QtCore.QRect(180, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lablOredrs.setFont(font)
        self.lablOredrs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lablOredrs.setTextFormat(QtCore.Qt.AutoText)
        self.lablOredrs.setObjectName("lablOredrs")
        self.pushButtonReady_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReady_2.setGeometry(QtCore.QRect(740, 130, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonReady_2.setFont(font)
        self.pushButtonReady_2.setStyleSheet("background-color: rgb(13, 103, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonReady_2.setObjectName("pushButtonReady_2")
        self.pushButtonReady_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReady_3.setGeometry(QtCore.QRect(740, 230, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonReady_3.setFont(font)
        self.pushButtonReady_3.setStyleSheet("background-color: rgb(13, 103, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonReady_3.setObjectName("pushButtonReady_3")
        self.pushButtonCooking_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCooking_2.setGeometry(QtCore.QRect(520, 230, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonCooking_2.setFont(font)
        self.pushButtonCooking_2.setStyleSheet("background-color: rgb(150, 246, 84);\n"
"color: rgb(3, 0, 0);")
        self.pushButtonCooking_2.setObjectName("pushButtonCooking_2")
        self.listOrders_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.listOrders_2.setGeometry(QtCore.QRect(50, 230, 391, 71))
        self.listOrders_2.setObjectName("listOrders_2")
        self.pushButtonReady_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReady_4.setGeometry(QtCore.QRect(740, 330, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonReady_4.setFont(font)
        self.pushButtonReady_4.setStyleSheet("background-color: rgb(13, 103, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonReady_4.setObjectName("pushButtonReady_4")
        self.listOrders_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.listOrders_3.setGeometry(QtCore.QRect(50, 330, 391, 71))
        self.listOrders_3.setObjectName("listOrders_3")
        self.pushButtonCooking_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCooking_3.setGeometry(QtCore.QRect(520, 330, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonCooking_3.setFont(font)
        self.pushButtonCooking_3.setStyleSheet("background-color: rgb(150, 246, 84);\n"
"color: rgb(3, 0, 0);")
        self.pushButtonCooking_3.setObjectName("pushButtonCooking_3")
        cookWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cookWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1285, 23))
        self.menubar.setObjectName("menubar")
        cookWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cookWindow)
        self.statusbar.setObjectName("statusbar")
        cookWindow.setStatusBar(self.statusbar)

        self.retranslateUi(cookWindow)
        QtCore.QMetaObject.connectSlotsByName(cookWindow)

    def retranslateUi(self, cookWindow):
        _translate = QtCore.QCoreApplication.translate
        cookWindow.setWindowTitle(_translate("cookWindow", "ДОБАВИТЬ ПОЛЬЗОВАТЕЛЯ"))
        self.labelTitleWindow.setText(_translate("cookWindow", "<html><head/><body><p align=\"center\">Панель Повара</p></body></html>"))
        self.pushButtonCooking.setText(_translate("cookWindow", "Готовится"))
        self.lablOredrs.setText(_translate("cookWindow", "<html><head/><body><p align=\"center\">Заказы</p></body></html>"))
        self.pushButtonReady_2.setText(_translate("cookWindow", "Готов"))
        self.pushButtonReady_3.setText(_translate("cookWindow", "Готов"))
        self.pushButtonCooking_2.setText(_translate("cookWindow", "Готовится"))
        self.pushButtonReady_4.setText(_translate("cookWindow", "Готов"))
        self.pushButtonCooking_3.setText(_translate("cookWindow", "Готовится"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cookWindow = QtWidgets.QMainWindow()
    ui = Ui_cookWindow()
    ui.setupUi(cookWindow)
    cookWindow.show()
    sys.exit(app.exec_())
